services:
- slug: homepage
  name: Homepage
  description: 当前仪表盘服务
  access_url: http://127.0.0.1:5173
  icon: https://www.google.com/s2/favicons?sz=128&domain_url=http://127.0.0.1:5173
  container: homepage
  tags:
  - dashboard
  require_probe: false
  managed: true
- slug: npm
  name: Nginx Proxy Manager
  description: 反向代理管理面板
  access_url: https://npm.chenfeiyu.cc:55110
  icon: https://www.google.com/s2/favicons?sz=128&domain_url=https://npm.chenfeiyu.cc
  container: nginx-proxy-manager
  tags:
  - reverse-proxy
  probe:
    url: https://npm.chenfeiyu.cc:55110
  require_probe: false
  managed: true
- slug: emby
  name: Emby Server
  description: 多媒体服务器
  access_url: http://192.168.50.7:8096
  icon: https://www.google.com/s2/favicons?sz=128&domain_url=http://192.168.50.7:8096
  container: emby
  tags:
  - media
  probe:
    url: http://192.168.50.7:8096
  stats:
    type: emby
    url: http://192.168.50.7:8096
    api_key: CHANGE_ME
  require_probe: false
  managed: true
- slug: nextcloud
  name: Nextcloud
  description: 个人云盘
  access_url: http://192.168.50.7:9999
  icon: https://www.google.com/s2/favicons?sz=128&domain_url=http://192.168.50.7:9999
  tags:
  - storage
  require_probe: false
  managed: true
